Number of interaction: 1000000
Output directory: "./out/memory_test/"
# Define the way we want to save the simulation:
# Among "Last" (Only final state), "Freq" (Require additional field "Number of save"), "Off" (No save)
Save mode: "Freq"
Number of save: 100
Verbose: True # Default False
# "Seed" of this simulation (identifier to avoid dublon)
Seed: "init"

# Model parameters
Community size: 75
Trust threshold: 0.6
Memory size: 100
Initial offset: 0 # Initial offset of the phenotype based strategies

# Valid phenotypes (with caps): Trustful, Random, Optimistic, Pessimist, Envious
Strategy distributions:
  Envious: 0.3
  Optimist: 0.2
  Pessimist: 0.21
  Random: 0.12
  Trustful: 0.17